"""测试 gcc 包"""
import shutil
import subprocess
from pathlib import Path

import pytest
from tests.lib.xpkg_parser import parse_xpkg
from tests.lib.assertions import (
    assert_required_fields, assert_valid_spec, assert_valid_type,
    assert_no_typos, assert_no_exec_xvm, assert_no_bashrc_modification,
    assert_no_direct_path_modification, assert_uses_new_api,
    assert_xim_add_succeeds, assert_install_succeeds,
    assert_command_output, assert_xvm_registered,
)
from tests.lib.platform_utils import skip_if_not

PKG = "gcc"
PKG_FILE = "pkgs/g/gcc.lua"

REPO = Path(__file__).resolve().parent.parent.parent
PRUNE_HARNESS = REPO / "tests" / "lua" / "gcc_prune_fixincludes_harness.lua"
FIXINCLUDES_BANNER = "auto-edited by fixincludes"


@pytest.fixture(scope='module')
def meta():
    return parse_xpkg(PKG_FILE)


class TestStatic:
    @pytest.mark.static
    def test_required_fields(self, meta):
        assert_required_fields(meta)

    @pytest.mark.static
    def test_valid_spec(self, meta):
        assert_valid_spec(meta)

    @pytest.mark.static
    def test_valid_type(self, meta):
        assert_valid_type(meta)

    @pytest.mark.static
    def test_no_typos(self):
        assert_no_typos(PKG_FILE)


class TestIndex:
    @pytest.mark.index
    def test_xim_add(self):
        assert_xim_add_succeeds(PKG_FILE)


class TestIsolation:
    @pytest.mark.isolation
    def test_no_exec_xvm(self):
        assert_no_exec_xvm(PKG_FILE)

    @pytest.mark.isolation
    def test_no_bashrc(self):
        assert_no_bashrc_modification(PKG_FILE)

    @pytest.mark.isolation
    def test_no_path_modification(self):
        assert_no_direct_path_modification(PKG_FILE)

    @pytest.mark.isolation
    def test_new_api(self):
        assert_uses_new_api(PKG_FILE)


class TestSubosPath:
    """gcc 记录到 xvm 的 subos 路径必须是可移植写法。

    xvm 版本库是**整个 home 共享**的一份，而 sysroot 是 per-subos 的。写死安装
    那一刻活动的 subos，对装 gcc 的那个 subos 正确、对其余全部错误 —— 用户切了
    subos，g++ 还在对着旧的头文件编译。写 `subos/current`（`self init` 建立、
    `subos use --global` 维护的 symlink）不需要占位符也不需要新字段。

    LINK 轴（loader/rpath，写进 payload 的 specs）方向相反：payload 全 home 共享
    且可以被绕过 shim 直接调用，所以那里**不许**出现 subos 路径。两条轴一起断言，
    否则改对一条会掩盖另一条。
    """

    @pytest.mark.static
    def test_alias_sysroot_uses_the_marker(self):
        src = open(PKG_FILE, encoding='utf-8').read()
        assert '${XLINGS_DYNAMIC_SUBOS_DIR}' in src, (
            "alias 的 --sysroot 必须写 xlings 的 marker；"
            "写死活动 subos 会让其他 subos 里的 g++ 用错头文件"
        )
        # marker 必须真的进了 alias，而不是只出现在注释里
        assert "alias_args = ' --sysroot=${XLINGS_DYNAMIC_SUBOS_DIR}'" in src

    @pytest.mark.static
    def test_alias_does_not_bake_a_concrete_subos(self):
        """subos_sysrootdir() 求值出的是**当前**活动 subos —— 它可以用于物化
        （往那棵树里装东西），但绝不能进 alias：alias 存在共享的版本库里。"""
        src = open(PKG_FILE, encoding='utf-8').read()
        alias_region = src.split('-- HEADER axis')[-1].split('xvm.add("xim-gnu-gcc"')[0]
        assert 'subos_sysrootdir' not in alias_region, (
            "alias 区域不得出现 subos_sysrootdir()：那会把安装时的 subos 烧进"
            "一个所有 subos 共享的记录里"
        )

    @pytest.mark.static
    def test_specs_rewrite_stays_payload_direct(self):
        src = open(PKG_FILE, encoding='utf-8').read()
        # specs 走 rpath + 动态链接器，两者都必须指向 payload
        assert 'pkginfo.install_dir(), "lib64"' in src, (
            "specs 的 rpath 必须是 payload-direct"
        )
        assert 'subos_sysrootdir' not in src.split('__rewrite_specs_linux')[-1], (
            "specs 重写路径里不得出现 subos —— payload 是全 home 共享的，"
            "而且直接调用 <install_dir>/bin/gcc 时根本不经过任何 subos"
        )


def _lua_interpreter():
    return shutil.which("lua5.4") or shutil.which("lua")


needs_lua = pytest.mark.skipif(
    _lua_interpreter() is None,
    reason="no lua interpreter on this machine",
)


def _build_include_fixed_tree(install_dir: Path) -> Path:
    """<install_dir>/lib/gcc/x86_64-linux-gnu/15.1.0/include-fixed/, holding
    one fixincludes-frozen header (carries the banner) and two files that
    fixincludes' own build step generates without a banner and that must
    survive the prune (README, limits.h)."""
    d = install_dir / "lib" / "gcc" / "x86_64-linux-gnu" / "15.1.0" / "include-fixed"
    d.mkdir(parents=True)
    (d / "pthread.h").write_text(
        "/*  DO NOT EDIT THIS FILE.\n\n"
        "    It has been " + FIXINCLUDES_BANNER + " from:\n\n"
        '\t"/usr/include/pthread.h"\n\n'
        "    This had to be done to correct non-standard usages in the\n"
        "    original, manufacturer supplied header file.  */\n"
        "#define PTHREAD_COND_INITIALIZER { 0 }\n"
    )
    (d / "limits.h").write_text(
        "/* Generated by fixincludes' companion mkfixinc.sh, not by the\n"
        " * fixincludes edit pass itself; carries no banner. */\n"
        "#include_next <limits.h>\n"
    )
    (d / "README").write_text(
        "This README file is copied into the directory for GCC-only header\n"
        "files when fixincludes is run.\n"
    )
    return d


def _run_prune(install_dir: Path, cwd: Path, variant: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [_lua_interpreter(), str(PRUNE_HARNESS), str(REPO / PKG_FILE),
         str(install_dir), variant],
        cwd=str(cwd), capture_output=True, text=True,
    )


class TestPruneStaleFixincludes:
    """__prune_stale_fixincludes() must locate the frozen header by the
    payload's own absolute path (pkginfo.install_dir()), never by whatever
    the calling process's current working directory happens to contain.

    Regression for the nested-quote defect fixed alongside this test: the
    previous call was
    `os.iorun(string.format("sh -c 'grep -rlF %s %s 2>/dev/null || true'",
    __shq(banner), __shq(root)))`. `__shq` single-quotes its argument, so the
    substituted banner and root arrived already single-quoted INSIDE an
    outer single-quoted `sh -c '...'` string; a POSIX shell cannot escape a
    quote with another quote of the same kind, so the outer shell split the
    command on those quote characters. The `grep` that actually ran received
    neither the full banner text nor `root` as a file operand, and GNU
    grep's `-r` with no operand recurses the CURRENT WORKING DIRECTORY
    instead. Run from a cwd unrelated to the payload -- the realistic case
    during an install -- that grep matched nothing and the prune was
    silently inert: no error, zero files removed, a payload identical to
    the one before the "fix" that was meant to clean it.

    This exercises the real recipe file (`pkgs/g/gcc.lua`) through a Lua
    sandbox (tests/lua/gcc_prune_fixincludes_harness.lua) against a synthetic
    tree, rather than installing gcc for real: an actual install pulls a
    multi-hundred-MB payload plus its own dependency closure (glibc,
    binutils, linux-headers), which is out of budget for the static/L0 tier
    this suite runs on every push. The harness reproduces both of libxpkg's
    os.iorun implementations (io.popen in the Lua prelude, std::system in
    the C++ executor) faithfully enough to matter here: neither raises on a
    non-zero exit, which is also why the removed `|| true` was never load-
    bearing, and only the C++ executor's capture-via-temp-file is exposed to
    the second trap named in the fix -- a trailing `|| true` appended
    without a protecting `sh -c '...'` binds the appended output redirect to
    `true` alone, so a real match's output never reaches the file read back.
    """

    @needs_lua
    @pytest.mark.parametrize("variant", ["prelude", "executor"])
    @pytest.mark.parametrize("cwd_kind", ["unrelated_empty", "payload_root"])
    @pytest.mark.static
    def test_prunes_the_frozen_header_regardless_of_cwd(self, tmp_path, variant, cwd_kind):
        install_dir = tmp_path / "install"
        d = _build_include_fixed_tree(install_dir)
        readme_before = (d / "README").read_bytes()
        limits_before = (d / "limits.h").read_bytes()

        unrelated_cwd = tmp_path / "unrelated_cwd"
        unrelated_cwd.mkdir()
        cwd = unrelated_cwd if cwd_kind == "unrelated_empty" else install_dir

        r = _run_prune(install_dir, cwd, variant)

        assert "PRUNE done" in r.stdout, r.stdout + r.stderr
        assert not (d / "pthread.h").exists(), (
            f"pthread.h (carries the fixincludes banner) was not pruned "
            f"from cwd={cwd_kind}, variant={variant}; stdout={r.stdout!r}"
        )
        assert (d / "README").read_bytes() == readme_before, "README must be untouched"
        assert (d / "limits.h").read_bytes() == limits_before, "limits.h must be untouched"
        assert "removed 1 header" in r.stdout, r.stdout

    @needs_lua
    @pytest.mark.parametrize("variant", ["prelude", "executor"])
    @pytest.mark.static
    def test_logs_the_search_even_when_nothing_is_frozen(self, tmp_path, variant):
        """The zero case must still be logged, with the root and the count,
        so an install log can tell "the search ran and found nothing" apart
        from "the search never ran"."""
        install_dir = tmp_path / "install"
        d = install_dir / "lib" / "gcc" / "x86_64-linux-gnu" / "15.1.0" / "include-fixed"
        d.mkdir(parents=True)
        (d / "README").write_text("no frozen headers in this payload\n")

        r = _run_prune(install_dir, tmp_path, variant)

        assert "PRUNE done" in r.stdout, r.stdout + r.stderr
        assert "removed 0 header" in r.stdout, r.stdout
        assert str(install_dir / "lib" / "gcc") in r.stdout, r.stdout

    @needs_lua
    @pytest.mark.static
    def test_absent_lib_gcc_directory_logs_nothing(self, tmp_path):
        """The early return (no lib/gcc at all) must stay silent, which is
        precisely what makes it distinguishable from the logged zero case
        above."""
        install_dir = tmp_path / "install"
        install_dir.mkdir()

        r = _run_prune(install_dir, tmp_path, "prelude")

        assert "PRUNE done" in r.stdout, r.stdout + r.stderr
        assert "fixincludes prune searched" not in r.stdout, r.stdout


class TestLifecycle:
    @pytest.mark.lifecycle
    @skip_if_not('linux')
    def test_install(self):
        assert_install_succeeds(PKG)


class TestVerify:
    @pytest.mark.verify
    @skip_if_not('linux')
    def test_gcc(self):
        assert_command_output("gcc --version | head -1", contains="gcc")

