package = {
    spec = "2",

    homepage = "https://rocm.docs.amd.com/projects/HIP/",
    name = "hip-nvidia",
    description = "HIP headers for the NVIDIA platform: the HIP API as a header layer over the CUDA runtime",

    authors = {"Advanced Micro Devices, Inc."},
    licenses = {"MIT"},
    repo = "https://github.com/ROCm/HIP",
    docs = "https://rocm.docs.amd.com/projects/HIP/en/latest/",

    type = "package",
    -- Headers only, so the payload is the same bytes everywhere; both
    -- architectures are listed because both can host a CUDA toolkit.
    archs = {"x86_64", "aarch64"},
    status = "stable",
    categories = {"gpu", "compute", "headers"},
    keywords = {"hip", "rocm", "cuda", "gpu", "portability"},

    -- WHAT THIS PACKAGE IS, AND WHY IT CONTAINS NO BINARIES.
    --
    -- HIP has two platforms. On AMD hardware it is a runtime library that
    -- talks to ROCm. On NVIDIA hardware it is a HEADER LAYER: every HIP entry
    -- point is an inline wrapper over the CUDA one, `hipError_t` is
    -- `cudaError_t` under a typedef, and the object a compiler produces links
    -- against the CUDA runtime and nothing of ROCm's. `hip/hip_runtime.h`
    -- chooses between the two by `__HIP_PLATFORM_AMD__` and
    -- `__HIP_PLATFORM_NVIDIA__` and refuses if neither or both are defined.
    --
    -- So this package publishes the NVIDIA half and nothing else. The device
    -- compiler is the one the project already resolved -- clang with
    -- `-x cuda`, or nvcc -- and the runtime is `xim:cuda-cudart`. There is
    -- no second toolchain to install and no ROCm on the machine.
    --
    -- WHY THREE UPSTREAM REPOSITORIES.
    --
    -- ROCm splits these headers across three releases at the same tag:
    -- `ROCm/HIP` carries the platform-agnostic API, `ROCm/hipother` carries
    -- `nvidia_detail`, and `ROCm/clr` carries `amd_detail`. The third is not
    -- optional on this platform: `hip_runtime_api.h` includes
    -- `hip/amd_detail/amd_hip_runtime_pt_api.h` UNCONDITIONALLY, on either
    -- platform, so a payload assembled from the first two alone fails to
    -- parse -- which is what the first assembly of this payload did.
    --
    -- `include/hip/hip_version.h` is a build product, generated by ROCm's
    -- CMake and therefore in none of the three source trees. The payload
    -- carries it generated from the HIP tree's own `VERSION` file, in the form
    -- that CMake emits. Of its macros the 7.2 headers reference
    -- HIP_VERSION_MAJOR, HIP_VERSION_MINOR, HIP_VERSION_PATCH and
    -- `__HIP_HAS_GET_PCH`; the last is 0 because the precompiled-header entry
    -- point it guards is implemented in the AMD runtime.
    --
    -- MEASURED: with these headers, `xim:cuda-cudart` 12.9.79 and clang 22
    -- from `xim:llvm`, a `.hip` translation unit compiled `-x cuda
    -- --cuda-gpu-arch=sm_89 -D__HIP_PLATFORM_NVIDIA__` produced an object,
    -- linked against `-lcudart_static`, and ran a `hipLaunchKernelGGL` kernel
    -- on an RTX 4080.
    xpm = {
        linux = {
            ["latest"] = { ref = "7.2.4" },
            ["7.2.4"] = {
                url = {
                    GLOBAL = "https://github.com/xlings-res/hip-nvidia/releases/download/7.2.4/hip-nvidia-7.2.4-noarch.tar.gz",
                    CN     = "https://gitcode.com/xlings-res/hip-nvidia/releases/download/7.2.4/hip-nvidia-7.2.4-noarch.tar.gz",
                },
                sha256 = "74e7483776409ec358b7d265ec3752a3466f326b007d8b1922b5f4bad47e3bc1",
            },
        },
    },
}

import("xim.libxpkg.pkginfo")
import("xim.libxpkg.log")
import("xim.libxpkg.xvm")
import("xim.libxpkg.system")
import("xim.pkgindex.sysroot")

function install()
    local dir = pkginfo.install_dir()
    os.tryrm(dir)

    local top = "hip-nvidia-" .. pkginfo.version()
    if not os.isdir(top) then
        log.error("hip-nvidia: expected %s in the extracted archive", top)
        return false
    end
    os.mv(top, dir)

    -- The dispatch header and both platform trees, checked by name. A payload
    -- missing `nvidia_detail` still installs, still has an `include/hip`, and
    -- fails at the first `#include` in a user's build with a message about a
    -- file rather than about this package.
    for _, required in ipairs({ "include/hip/hip_runtime.h",
                                "include/hip/hip_version.h",
                                "include/hip/nvidia_detail/nvidia_hip_runtime.h",
                                "include/hip/amd_detail/amd_hip_runtime_pt_api.h" }) do
        if not os.isfile(path.join(dir, required)) then
            log.error("hip-nvidia: payload is incomplete; missing %s", required)
            return false
        end
    end
    return true
end

function config()
    local dir = pkginfo.install_dir()
    local binding = package.name .. "@" .. pkginfo.version()

    -- No programs: this package registers a root so its headers have a node
    -- to hang from, and places nothing on PATH.
    xvm.add(package.name)

    -- _tree, not declare_headers: `include/hip/` is a namespace this package
    -- owns entirely today, but declaring the directory as one asset is a
    -- rename(2) over the sysroot's copy, and a future package contributing to
    -- the same namespace would silently replace it. The recursive form places
    -- files and survives that.
    if not sysroot.declare_headers_tree(dir, "include", "usr/include", binding) then
        sysroot.install_headers_tree(path.join(dir, "include"),
                                     path.join(system.subos_sysrootdir(), "usr", "include"))
    end
    return true
end

function uninstall()
    xvm.remove(package.name)
    os.tryrm(pkginfo.install_dir())
    return true
end
