-- Android debug keystore -- one `debug.keystore` file, signed with the
-- alias, password and distinguished name Android's own tooling has used for
-- every debug build since the platform's first release.
--
-- WHY THIS IS A PACKAGE, AND WHY THE RULE WOULD OTHERWISE BE BROKEN FIRST
-- HERE. `mcpp:plugins`' `dist-apk` member (design record mcpp .agents/docs/
-- 2026-09-12-622-a-ui-framework-on-android-ios-and-web.md, section 3.2)
-- signs a debug APK with `apksigner sign --ks <keystore>`. Android's own
-- tooling (`adb`, Android Studio, the Gradle plugin) generates this file
-- itself, on first need, under `~/.android/debug.keystore` -- a path outside
-- any package store, different bytes on every machine, written by a
-- `keytool` run at BUILD time. That is exactly the host-path model the
-- design record's rule 9 excludes ("a tool, a data file, a keystore, a
-- runtime stub reach a build program through a declared `xim:` package and
-- `xpkg_dir`, never through `~/.something`"), and of the cases that rule
-- lists, this is the one whose ordinary implementation is a `~/.` path by
-- convention across the entire Android ecosystem, not by an oversight of
-- this index -- so it is the case where the rule would have been broken
-- first, and it is what this package exists to not do.
--
-- Because the alias (`androiddebugkey`), both passwords (`android`), and
-- the distinguished name (`CN=Android Debug,O=Android,C=US`) are the exact
-- values Android's own build tooling has published and used since the
-- platform's first SDK release, publishing this file's bytes discloses
-- NOTHING: a debug key's only security property is that it is not a
-- release key, and every Android developer's own machine already carries a
-- functionally-equivalent one. This package makes that key IDENTICAL on
-- every machine and in CI rather than merely equivalent in shape, which is
-- what lets a debug APK built by one machine be reinstalled over one built
-- by another without an uninstall -- the same signature, byte for byte.
--
-- ═══════════════════════════════════════════════════════════════════════
-- HOW THIS FILE WAS PRODUCED (once; NOT reproduced on every recipe change)
-- ═══════════════════════════════════════════════════════════════════════
--
-- Generated 2026-09-12 with `xim:jdk-temurin`'s own `bin/keytool` (25.0.4+7,
-- resolved through this recipe author's own installed payload, not the
-- system's):
--
--   keytool -genkeypair -v \
--     -keystore debug.keystore \
--     -storepass android \
--     -alias androiddebugkey \
--     -keypass android \
--     -keyalg RSA \
--     -keysize 2048 \
--     -validity 10000 \
--     -dname "CN=Android Debug,O=Android,C=US"
--
-- Output (2666 bytes; `keytool -list -v` against it, verified before
-- publishing): a PKCS12 keystore, one entry, alias `androiddebugkey`, a
-- self-signed 2048-bit RSA certificate under `CN=Android Debug, O=Android,
-- C=US`, signature algorithm `SHA384withRSA`, valid from 2026-09-12 until
-- 2054-01-28 (10,000 days).
--
-- THIS COMMAND MUST NEVER BE RE-RUN TO "REFRESH" THE ASSET. `keytool
-- -genkeypair` draws a fresh RSA keypair every invocation regardless of how
-- identical the flags are; running it twice produces two different keys
-- under the same distinguished name. The asset xlings-res publishes for
-- `1.0.0` is generated exactly once and republished byte-for-byte for as
-- long as this recipe's version says `1.0.0` -- a version bump here means a
-- genuinely different key was needed (it should not be), not routine
-- maintenance. See `.upload/UPLOAD.md` in this repository's own working
-- tree (untracked; the keystore itself is never committed) for the sha256
-- this version's table below was written from and the exact upload this
-- package still needs before it resolves.
--
-- ═══════════════════════════════════════════════════════════════════════
-- LICENCE / OWNERSHIP
-- ═══════════════════════════════════════════════════════════════════════
--
-- This file is not upstream's; it is generated by this recipe's own author
-- using a publicly documented convention (Android's own debug-signing
-- documentation names the identical alias, password and validity period).
-- `licenses = {"Apache-2.0"}` matches the index's own repo licence, the same
-- choice `apple-simulator-tools.lua` makes for its own recipe-authored
-- script -- there is no upstream licence to read because there is no
-- upstream artifact, only a documented convention this recipe reproduces.
--
-- ═══════════════════════════════════════════════════════════════════════
-- HOST INDEPENDENT
-- ═══════════════════════════════════════════════════════════════════════
--
-- A keystore file's bytes carry no host or architecture information --
-- `keytool`'s own PKCS12 output format is identical regardless of the
-- machine that ran it -- so one sha256 serves linux, macosx and windows
-- alike, the same shape `pkgs/p/picolibc-riscv.lua` uses for its own
-- host-independent target sysroot (docs/contributing.md ss5.2: "载荷与宿主无
-- 关 => 一个 sha256 服务全平台").
--
-- No `ci` block, for the identical reason `picolibc-riscv.lua` states for
-- its own self-built artifact: `mirror = true` would point xlings-res's
-- mirror at itself, and `update = true` would move `latest` to a version
-- this file was never regenerated for. A version bump here is a human step
-- (regenerate deliberately, which this header says not to do lightly;
-- publish; edit this file).
--
-- ═══════════════════════════════════════════════════════════════════════
-- INSTALLED LAYOUT
-- ═══════════════════════════════════════════════════════════════════════
--
--   <install_dir>/debug.keystore     the one file this package provides.
package = {
    spec = "2",
    homepage = "https://developer.android.com/studio/publish/app-signing#debug-mode",

    name = "android-debug-keystore",
    description = "The Android debug-signing keystore, published once so every machine and CI signs debug APKs identically",

    authors = {"mcpplibs"},
    maintainers = {"d2learn"},
    licenses = {"Apache-2.0"},
    repo = "https://github.com/openxlings/xim-pkgindex",
    docs = "https://developer.android.com/studio/publish/app-signing#debug-mode",

    type = "package",
    archs = {"x86_64", "aarch64"},
    status = "stable",
    categories = {"android", "signing", "data"},
    keywords = {"android", "apk", "debug", "keystore", "apksigner", "signing"},

    xvm_enable = true,

    -- See "HOW THIS FILE WAS PRODUCED" above for the sha256's origin and
    -- `.upload/UPLOAD.md` (untracked) for the exact xlings-res asset this
    -- entry resolves once published. `source` at the root, not per host,
    -- because HOST INDEPENDENT above means all three hosts want the same
    -- URL shape and the same single sha256.
    xpm = {
        source = {
            GLOBAL = "https://github.com/xlings-res/android-debug-keystore/releases/download/${version}/debug.keystore",
            CN = "https://gitcode.com/xlings-res/android-debug-keystore/releases/download/${version}/debug.keystore",
        },
        linux = {
            ["latest"] = { ref = "1.0.0" },
            ["1.0.0"] = { sha256 = "f5394989198294ac164f88d612f9971c64135b7d86df590d5afbc9c1810e9aa0" },
        },
        macosx = {
            ["latest"] = { ref = "1.0.0" },
            ["1.0.0"] = { sha256 = "f5394989198294ac164f88d612f9971c64135b7d86df590d5afbc9c1810e9aa0" },
        },
        windows = {
            ["latest"] = { ref = "1.0.0" },
            ["1.0.0"] = { sha256 = "f5394989198294ac164f88d612f9971c64135b7d86df590d5afbc9c1810e9aa0" },
        },
    },
}

import("xim.libxpkg.pkginfo")
import("xim.libxpkg.xvm")
import("xim.libxpkg.log")

function install()
    -- The download IS the file: no archive, nothing to extract. Same shape
    -- pkgs/b/bazel.lua uses for its own single-file payload.
    os.tryrm(pkginfo.install_dir())
    os.mkdir(pkginfo.install_dir())

    local dest = path.join(pkginfo.install_dir(), "debug.keystore")
    os.mv(pkginfo.install_file(), dest)

    if not os.isfile(dest) then
        raise("android-debug-keystore: " .. dest .. " was not written")
    end

    log.debug("android-debug-keystore: wrote %s", dest)
    return true
end

function config()
    -- Umbrella only: this package provides a data file, not a program, so
    -- there is no `bin/<name>` to shim -- the same `type = "group"` idiom
    -- `android-ndk.lua` and `pkgs/a/android-platform.lua` both use for a
    -- payload with nothing to dispatch. A consumer (`dist-apk`) reaches the
    -- file with `pkginfo.dep_install_dir("xim:android-debug-keystore")` and
    -- joins `"debug.keystore"` itself, never through a shim or PATH.
    xvm.add(package.name, { type = "group" })
    return true
end

function uninstall()
    xvm.remove(package.name)
    return true
end
